clc
clear all
X=xlsread('INPUT');
Y=xlsread('OUTPUT');
Z=inv(X'*X);
%BETA MATRIX
B=Z*(X'*Y);
B
%PRIDUCTED Y VALUE
YP=X*B;
%ERROR
E=Y-YP;
E
%ERROR SQUARE
ES=E.^2
SSE=sum(ES(:,1))
%GIVEN DATA MEAN
GDM=(sum(Y(:,1)))/10
%CONVERTING DATA MEAN MATRIX TO 10X1 MATRIX 
GDMM(1:10,1)=GDM;
%REGRESSION SQUARE 
SR=(YP-GDMM).^2
%SUM OF SQUARE REGRESSION
SSR=sum(SR(:,1))
%R SQUARE VALUE
RS=(SSR)/(SSR+SSE)
%PLOT(OUTPUT VS REGRESSION PLOT)
plot(Y,YP)

